### ISSUE TITLE
Predictive - Corrective SPH ?

### ISSUE THREAD

**Issue by Al-th** [cerrno/pcisph#1]
Hi,

I was wondering which SPH formulation you implemented here. Unlike the title of this repo, it does not look like the "Predictive Corrective SPH" from Solenthaler.

Could you point me to the paper you implemented in this PCISPH code ? 

Thanks in advance,

Al-th

**Comment by lucas-schuermann** [comment]
It's not exactly the PCISPH, but it can be viewed as 1-iteration of SPH relaxation plus sub-stepping. The “prediction-relaxation” scheme of my implementation actually comes mainly from the (much easier to follow) paper "Particle-based Viscoelastic Fluid Simulation”, as opposed to "Predictive-Corrective Incompressible SPH”.
