### ISSUE TITLE
I have an error when making the project

### ISSUE THREAD

**Issue by chouss911** [cerrno/pcisph#3]
![image](https://user-images.githubusercontent.com/92730002/237028985-f5d76ad4-5451-41e4-956e-b2979cae5dff.png)
could u tell me how to  solve it?

**Comment by lucas-schuermann** [comment]
Looks like you're building using the MacOS library paths. Try uncommenting the paths under `# Linux` in the Makefile.

**Comment by chouss911** [comment]
Thanks,I've sovled it successfully！
